<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPOGW9j8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPOGW9j8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPOGW9j8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPOGW9j8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPOGW9j8\App_KernelDevDebugContainer([
    'container.build_hash' => 'POGW9j8',
    'container.build_id' => 'cdc75dd3',
    'container.build_time' => 1709110940,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPOGW9j8');
